#!/usr/bin/env ruby
#
# An example hook script to blocks unannotated tags from entering.
# Called by "git receive-pack" with arguments: refname sha1-old sha1-new
#
# To enable this hook, rename this file to "update".
#
# Config
# ------
# hooks.allowunannotated
#   This boolean sets whether unannotated tags will be allowed into the
#   repository.  By default they won't be.
# hooks.allowdeletetag
#   This boolean sets whether deleting tags will be allowed in the
#   repository.  By default they won't be.
# hooks.allowmodifytag
#   This boolean sets whether a tag may be modified after creation. By default
#   it won't be.
# hooks.allowdeletebranch
#   This boolean sets whether deleting branches will be allowed in the
#   repository.  By default they won't be.
# hooks.denycreatebranch
#   This boolean sets whether remotely creating branches will be denied
#   in the repository.  By default this is allowed.
#

# --- Command line
$refname = ARGV[0]
$oldrev  = ARGV[1]
$newrev  = ARGV[2]

#$command = "git log --pretty=format:'%an, %cn' " <<  $oldrev << ".." << $newrev << "  >> /usr/local/myproject/pomodoro/refname"
#$log = system($command )
if $refname != "refs/heads/master"
# system( $log << " >> /usr/local/myproject/pomodoro/refname")
 #fl = open("/usr/local/myproject/pomodoro/refname", 'a')
 #fl.print $refname
 #fl.close
 system("touch ./null")
 system("chmod 600 ./null")
 system("wget -O ./null http://jenkins.pilgrim-lifestyle.com:8080/job/pomodoro-personal/build?token=POMODORO_SAMPLE")
 system("rm -rf ./null")
end
